aeternity/aepp-cli-js

bin/aecli-account.js, bin/aecli-contract.js, bin/aecli-name.js, bin/utils/cli.js, package.json, test/cli/contract.test.js
Add contract test's for type-cheked contract call
=> Add --native to `aecli` (Build transaction's natively)

README.md
I was having issues setting up the symlink, the `npm link` to `./bin/aecli.js` line made it a bit confusing. Defined correct steps to symlink.
=> add local symlink documentation

bin/aecli-contract.js, bin/commands/contract.js, bin/utils/cli.js, package.json, test/cli/account.js, test/cli/contract.test.js, test/cli/index.js
Change contract compile/deploy command (SDK BREAKING CHANGES)
Change contract test
Add --compilerUrl to contract module
=> Update sdk version to 2.4.0

bin/commands/inspect.js, bin/utils/constant.js, package-lock.json, package.json
=> feat(Inspect): Add ability to inspect raw tx

bin/commands/account.js, bin/commands/aens.js, bin/utils/account.js
Fixed: https://github.com/aeternity/aepp-cli-js/issues/89, https://github.com/aeternity/aepp-cli-js/issues/88
=> fix(Account): Fix --json for account commands

CHANGELOG.md, bin/aecli-account.js, bin/commands/account.js, bin/utils/account.js, bin/utils/print.js, package-lock.json, package.json, test/cli/account.js, test/cli/chain.test.js
* **ACCOUNT:** Add command for generating and printing bulk of Key Pairs ([#95](https://github.com/aeternity/aepp-cli-js/issues/95)) ([1cb3e5b](https://github.com/aeternity/aepp-cli-js/commit/1cb3e5b))
=> Release 2.4.0

.env, CHANGELOG.md, package-lock.json, package.json
* **Node** Node 5.0.0-rc1 compatibility
=> Release 2.5.0

.env, .github/ISSUE_TEMPLATE.md, CHANGELOG.md, README.md, bin/aecli-contract.js, bin/aecli-tx.js, bin/commands/contract.js, bin/commands/transaction.js, bin/utils/constant.js, bin/utils/helpers.js, docker-compose.yml, docker/aeternity_node_mean16.yaml, docs/bin/aecli-account.md, docs/bin/aecli-contract.md, docs/bin/aecli-tx.md, docs/bin/commands/account.md, docs/bin/commands/aens.md, docs/bin/commands/contract.md, docs/bin/commands/transaction.md, docs/bin/utils/account.md, docs/bin/utils/constant.md, docs/bin/utils/helpers.md, docs/bin/utils/print.md, package-lock.json, package.json, test/cli/contract.test.js, test/cli/inspect.test.js, test/cli/tx.js
* **Lima:** Add support for lima ([#105](https://github.com/aeternity/aepp-cli-js/issues/105)) ([f7b061a](https://github.com/aeternity/aepp-cli-js/commit/f7b061a))
* **Compiler:** Add `backend` option to compiler(Can be `fate` or `aevm`. `fate` by default)
* **AENS:** Add `nameFee` option to `claim` command
=> Release 2.6.0

bin/aecli-name.js, bin/commands/aens.js, test/cli/aens.test.js, test/cli/index.js, test/cli/tx.js
Add additional option `extendPointers` for `update` command which allow to extend pointer instead of overwriting them
Fix test's
=> feat(AENS): Fix BC for all of AENS commands.

bin/commands/chain.js, bin/utils/errors.js
=> print API error message, add Iris protocol version

CLI.md, README.md, babel.config.js, babel.tests.config.js, package-lock.json, package.json, src/aecli.js, src/utils/print.js
depends on #176 
Firstly it is interesting as technology, also this would improve stack traces from sdk to make debugging easier
=> chore(babel): build to es modules

package.json, src/actions/contract.js, src/actions/transaction.js, src/arguments.js, src/commands/contract.js, src/commands/tx.js, src/utils/cli.js, src/utils/helpers.js, src/utils/print.js, test/chain.js, test/contract.js, test/name.js, test/tx.js
depends on #179 
closes #167 
closes #168 
closes #171
=> Rearrange contract module

src/actions/account.js, src/actions/aens.js, src/actions/chain.js, src/actions/inspect.js, src/actions/oracle.js, src/aecli-account.js, src/aecli-chain.js, src/aecli-contract.js, src/aecli-crypto.js, src/aecli-inspect.js, src/aecli-name.js, src/aecli-oracle.js, src/aecli-tx.js, src/aecli.js, src/commands/contract.js, src/commands/crypto.js, src/utils/CliError.js, src/utils/account.js, src/utils/helpers.js
closes https://github.com/aeternity/aepp-cli-js/issues/191
depends on https://github.com/aeternity/aepp-cli-js/pull/193
=> feat: don't print stack traces for cli errors

.gitignore, package-lock.json, package.json, scripts/js-to-md.js, src/actions/account.js, src/actions/contract.js, src/commands/account.js, src/commands/contract.js, src/commands/crypto.js, src/utils/CliError.js, src/utils/account.js, src/utils/helpers.js, test/account.js, test/chain.js, test/contract.js, test/crypto.js, test/index.js, test/inspect.js, test/name.js, test/oracle.js, test/other.js, test/tx.js
=> Contract fixes

package-lock.json, package.json, src/actions/inspect.js, src/utils/constant.js, src/utils/helpers.js, src/utils/print.js, test/contract.js, test/tx.js
=> refactor: use sdk's Encoding instead of HASH_TYPES

src/utils/print.js, test/contract.js
closes #204 
```
$ aecli contract call --contractAddress ct_Fv9d66QTjr4yon9GEuMRc2B5y7Afy4to1ATaoYmpUTbN6DYiP --contractSource ./MintableMappedMetadataNFT.aes --callStatic metadata '[1]'
----------------------Call info-----------------------
Contract address ________________________ ct_Fv9d66QTjr4yon9GEuMRc2B5y7Afy4to1ATaoYmpUTbN6DYiP
Gas price _______________________________ 1000000000
Gas used ________________________________ 122383
Return value (encoded) __________________ cb_r4IAAQEbr4IBAQEbLwYRbmFtZVVXYWxraW5nIG9uIHRoZSBsYWRkZXIlbWVkaWFfdXJs1WlwZnM6Ly9RbWZDcjU4NmFIRlZrNnAyV2hUQzFLdmNhcHMyNE10bnkyQ0xCNWJzVFQ5TXZaKW1lZGlhX3R5cGUVSU1BR0UtZGVzY3JpcHRpb271VGhleSBhcmUgZXNjYXBpbmcgZnJvbSBlYXJ0aCBhbmQgc3RlcHBpbmcgaW50byB0aGUgbWV0YXZlcnNlIUltdXRhYmxlX2F0dHJpYnV0ZXM1eyJyZXRyaWVzIjowfVFpbW11dGFi …
```
=> fix(contract): stringify maps as arrays

CLI.md, README.md, src/commands/main.js
=> docs: fix description of contract module and commands list

package-lock.json, package.json, src/actions/contract.js, test/contract.js
closes #203 
found issues https://github.com/aeternity/aeproject/issues/433 https://github.com/aeternity/aeproject/issues/435
=> feat(contract): includes support

package-lock.json, package.json, src/utils/account.js, test/account.js
This PR is supported by the Æternity Crypto Foundation
=> fix(account): don't ask for password if it is empty

src/actions/contract.js, src/arguments.js, src/commands/contract.js, src/commands/tx.js, test/contract.js, test/contracts/contract.aes, test/tx.js
=> feat(contract): accept amount in contract and tx builder commands

src/actions/account.js, src/actions/aens.js, src/actions/chain.js, src/actions/contract.js, src/actions/inspect.js, src/actions/oracle.js, src/actions/transaction.js, src/arguments.js, src/commands/account.js, src/commands/chain.js, src/commands/contract.js, src/commands/inspect.js, src/commands/main.js, src/commands/name.js, src/commands/oracle.js, src/commands/spend.js, src/commands/tx.js, src/utils/cli.js, src/utils/helpers.js, src/utils/print.js, test/index.js, test/name.js, test/oracle.js, test/tx.js
=> Improve commands help, remove extra arguments in oracle commands

reference.md, src/arguments.js, src/commands/name.js, src/commands/oracle.js, src/commands/tx.js, user-guide.md
=> Extract options in tx builder

package-lock.json, package.json, reference.md, src/actions/account.js, src/actions/contract.js, src/actions/oracle.js, src/actions/transaction.js, src/aecli.js, src/arguments.js, src/commands/name.js, src/commands/oracle.js, src/commands/tx.js, src/utils/cli.js, src/utils/helpers.js, src/utils/keystore.js, src/utils/print.js, src/utils/sdk-defaults.js, test/account.js, test/chain.js, test/index.js, test/inspect.js, test/name.js, test/oracle.js, test/spend.js, test/tx.js, test/utils.js
=> Prepare sdk update

.mocharc.cjs, src/actions/aens.js, src/actions/contract.js, src/utils/print.js, test/account.js, test/contract.js, test/index.js, test/inspect.js, test/name.js, test/other.js, test/spend.js, test/tx.js, test/utils.js
=> Fix printing details of static call and improve tests
